language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "YfMfCguPVIaxh6qRc5QKNdxg0Mp+hrkZsuRFbl/v02qcm0wD16gnZD0/BHVSjVA3sD2SSCQ1YOydeKUrr8b4zpfsgsNoMq094YyJWHva4j79SY8vOW4Eyeot2sztF6qCN0gaXnrLpx96tSGdJENHOAZDXEvpr190fTL/A6TAQt3IzyfH8rfGvSPAsGR8Dpy3ne3YwR1my5PIZpQk6KrVbhZU6lGbXoBrsXdWs3DihLdYQeoYtgeBfZ+GB7m/lDmmJkYBXeWIPbJJ84DQU9q8hdwUlYVw89g2d4aZ5b31Nppft8GMj1HsIwPSjHF1OvHAOpC60lhbd65UYxf1lt1gybf+2b45LFqL8vI0mOvCakZojJjYC2SsTysy3kBzC1muqW7oLVy8sVvrTWq0M4zSa/ckcX20S7re7pCzUFR96WMjafDAnkb903Mb2CUS92CXFkehjOR6+vEd+cvlB7FNSBDTYtfZ7GcHkFF1ut1WbDKMQvNVaG+i/E7Mxc5bYnv4PcC2hBlQdyDnH+Nvsx9wRJY4Xzvdf2rzlk31Ad8dLHygMMiCt8ekMUQNv1/lgdrpppSZwkBi+lqWJljTOdGHUPn3EF80zmf1XResx2vdEwe8BPM6lO0AynWZ0OrYiB+NWbqPQBdNaW4SWWF/IRn9jYPz92O7GoggwScqf5J2IZg="