language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "1/BtjDGINmmAoO0yFIG4vrqLW6_HXkn4pK-UjVW5ZUaew"
  project: "my-spend-tracker"
